---
abstract: 'Parse and format W3CDTF datetime strings'
author:
  - 'Dave Rolsky <autarch@urth.org>'
  - 'Gregory Todd Williams <gwilliams@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::More: 0.61
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.19'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: DateTime-Format-W3CDTF
no_index:
  directory:
    - examples
    - inc
    - t
requires:
  DateTime: 0
  perl: 5.8.0
resources:
  bugtracker: https://github.com/kasei/datetime-format-w3cdtf/issues
  homepage: https://metacpan.org/release/DateTime-Format-W3CDTF/
  license: http://dev.perl.org/licenses/
  repository: https://github.com/kasei/datetime-format-w3cdtf
version: '0.08'
